
# portfolioDataSource: "/assets/data/portfolio-data.yaml"
portfolioDataSource: "https://raw.githubusercontent.com/Vaishnavi-Dontaraju/Vaishnavi-Dontaraju.github.io/main/assets/data/portfolio-data.yaml"
